### PR TITLE
Enhanced file structure for development version of VES.

### PR DESCRIPTION
**Pull request by uppusaikiran**
## Introduction

Instead of putting all the style sheets and scripts files in the root folder,it is better to move each file to separate folder which helps developers able to understand what really the functionality of each module.
## Things Done
1. Moved image assets to separate folders.
2. Main scripts are moved to scripts folder.
3. Entire background scripts are separated from base scripts and moved to background folder.
4. 2 Versions(Both Prod and Dev) of captcha.js is added.
5. Multiple DOM referencing is replaced with single DOM call and traversal functionality.
6. Instead of jquery.js a minified jquery.min.js is added for production environment.
7. Moved all the style-sheets to respective folders based on their usage.
8. Updated manifest file matching the modified changes.
9. Jquery functionality was added to options.js.
## Things yet to do
1. Change Main.js file and update functionality with jquery.
2.  ~~Move files to corresponding folders~~.
3. Remove css bugs in course page.
4. ~~Remove bugs introduced due to moving files.~~

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
@uppusaikiran Thanks for the PR! can you see and explain why there is no css for popup as it was there earlier and if there are any other major changes, please highlight it below.

**Comment by hvarday** [comment]
@uppusaikiran , Great work.. Much appreciated!
I found this bug,

> couldn't include calc.js ( change of path required )

**Comment by uppusaikiran** [comment]
Thanks @rahulkapoor90 and @hvarday for your response.

When modifying the file structure in a customized manner took some time as it has lot of referencing and files.Initially i have moved assets like images and css files seperately.Later i started working on scripts.This resulted in some bugs and majority of which are rectified previously.

#### Bug Fix - [#1](https://github.com/uppusaikiran/VITacademics-Enhancement-Suite/commit/0179b9c66ebe00fdbb75419196f363192574e0ae) (couldn't include calc.js ) by @hvarday

`The path of calc.js file in the web accesable resources is changed.`

#### Bug Fix - [#2](https://github.com/uppusaikiran/VITacademics-Enhancement-Suite/commit/efa0aa53979ed6737f445e5aac793e5e0809b837) (no css for popup) by @rahulkapoor90

`The href value points to invalid loacation and now fixed.And now popup has css.`

**Comment by rahulkapoor90** [comment]
@uppusaikiran okay, i accepted your pull request.

**Comment by uppusaikiran** [comment]
@rahulkapoor90 Thanks for accepting the pull request.

**Comment by rahulkapoor90** [comment]
No problem, keep on working on your other TODO items i will accept those too if they are good enough.

**Pull request merged**
