### PR TITLE
Fixed from date in attendance

### PR DESCRIPTION
**Pull request by uppusaikiran**
a simple fix can automatically populate the from date and which can be explicitly changed for every year to the start date of the year.

Tested and Fixed Bug.

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
Will this work in future?

**Comment by uppusaikiran** [comment]
Yes after the next sem starts we need to set the date to 1-JAN-2017 and it will work for 2 semesters.

**Comment by rahulkapoor90** [comment]
okay. any permanent solutions? i mean using js.

**Comment by uppusaikiran** [comment]
[**@rahulkapoor90**](https://github.com/rahulkapoor90) commented on [Dec 4, 2016, 10:27 PM GMT+5:30](https://github.com/rahulkapoor90/VITacademics-Enhancement-Suite/pull/19#issuecomment-264715615 "2016-12-04T16:57:51Z - Replied by Github Reply Comments"):
> okay. any permanent solutions? i mean using js.

I will try and update.

**Pull request merged**
