### PR TITLE
Updated spotlight page,given importance to message tab and minor other fixes.

### PR DESCRIPTION
**Pull request by uppusaikiran**
### Problem

 Everytime it is so frustrating the messages and spotlight marquees from bottom to top as we have to wait till reaches the place where we are intrested.
### Solution
1. Instead of marquee both , messages and spotlight tabs are made static.
2. We only want spotlight to appear for 5-10 seconds to see if any new events were there..
3. After 5-10 sec we dont need spotlight,but messages are very important.
4. After 5-10 sec spotlight tab hides from view and messages tab comes into focus.
5. Latest messages are displayed.
### Other minor fixes
1.  Added online payment portal into VES.
2.  Removed captcha box in change password.
3. Updated todos.

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
i don't think users would be willing to add spotlight auto hide after 5-10 seconds as you did just because what if user wants to view it for more time rather can you make it as click to open tabs.

Why there is google analytics for wifi login, i haven't added it anywhere else, plus i also did try to hide the captcha box but when the next page to enter OTP comes in forgot password page it is also hidden. have you fixed it?

plus TODO's are for highlighting what you will be doing next and maybe you have added what you have done please fix it and what is spotlight animation?

**Comment by uppusaikiran** [comment]
@rahulkapoor90 

Thanks for your suggestion about the spotlight hide feature,actually i thought students wont be interested in spotlight page after they looked for 10 seconds, instead they will be much interested in messages sent by faculty.But any how i have reverted the changes to original and also [deleted](https://github.com/rahulkapoor90/VITacademics-Enhancement-Suite/pull/3/commits/b8673da47f5be2cefad791702643c0cc13a1776b) the spotlight_animation.gif from Media/ .

Secondly,when we hide the captcha the OPT is also hiding,so lets treat this a [Bug](https://github.com/rahulkapoor90/VITacademics-Enhancement-Suite/pull/3/commits/a3dcc56b40c011b2831fe514a82729aafc24b643) and I will try to fix in subsequent update.

Regarding the readme to-dos I have updated the readme.

Lastly I wanted to add the google-analytics feature to the VES extension as It will help in analyzing the audience and improve to match the need of students.So just made a small google analytics feature , when ever the student click on the popup to login to his phonton account ,the google sends us message from google-analytics.

###### Sample analytics realtime data is here



#### Fixed Bugs

Added captcha support to online payment site also.

**Comment by rahulkapoor90** [comment]
Sorry, @uppusaikiran i can't allow google analytics anywhere in the extension as it violates user privacy and i have promised to make it as a priority please remove it for now, plus please mention what are the final changes this pull request is sending?

**Comment by uppusaikiran** [comment]
@rahulkapoor90 actually i want to close this pull request because i fell further improvement is needed to the pull request.

**Comment by rahulkapoor90** [comment]
Sure, but next time when you send a pull request do think about how user will be affected by the changes, will they like it and try to send small increments of pull requests so that i can easily review it, rest is fine. well done.

**Pull request closed without merging**
