### PR TITLE
Changed the custom menu font-size to be viewport based

### PR DESCRIPTION
**Pull request by abishekaditya**

### CODE REVIEW

**Comment by rahulkapoor90** [comment]
Thanks for the PR @abishekaditya

**Comment by rahulkapoor90** [comment]
chrome_2016-12-25_18-19-29 this is how it shows after your PR. not sure why it's needed? can you let me know more about your PR

**Comment by abishekaditya** [comment]
Before

Before

After

After

Hope this clears it

**Comment by rahulkapoor90** [comment]
Okay. I'll have to see how to maintain font size in full menu.

**Pull request merged**
